-- MySQL Script generated by MySQL Workbench
-- Revisado por GEPETO e Mateus em 09/11/2025

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, 
    SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetoautomov
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetoautomov` DEFAULT CHARACTER SET utf8;
USE `projetoautomov`;

-- -----------------------------------------------------
-- Tabela FUNCIONARIO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(65) NOT NULL,
  `telefone` CHAR(11) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `cargo` ENUM('Mecanico', 'Atendente', 'Gerente') NOT NULL,
  PRIMARY KEY (`id_funcionario`),
  UNIQUE INDEX `login_UNIQUE` (`login`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf`)
)
-- ENGINE define o "motor" da tabela. InnoDB permite usar FKs e transações.
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Tabela CLIENTE
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(65) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `telefone` CHAR(11) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Tabela VEICULO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veiculo` (
  `id_veiculo` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `marca` VARCHAR(30) NOT NULL,
  `modelo` VARCHAR(30) NOT NULL,
  `ano` CHAR(4) NULL,
  `cor` VARCHAR(30) NULL,
  `placa` CHAR(8) NOT NULL,
  `motor` CHAR(10) NOT NULL,
  PRIMARY KEY (`id_veiculo`),
  INDEX `fk_veiculo_cliente_idx` (`id_cliente`),
  CONSTRAINT `fk_veiculo_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Tabela ORDEM_SERVICO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordem_servico` (
  `id_ordem_servico` INT NOT NULL AUTO_INCREMENT,
  `id_veiculo` INT NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  `descricao_problema` TEXT NOT NULL,
  `acao_realizada` TEXT NOT NULL,
  `status` ENUM('aberta', 'em_andamento', 'concluida', 'cancelada') NOT NULL,
  PRIMARY KEY (`id_ordem_servico`),
  INDEX `fk_ordem_servico_veiculo_idx` (`id_veiculo`),
  CONSTRAINT `fk_ordem_servico_veiculo`
    FOREIGN KEY (`id_veiculo`)
    REFERENCES `veiculo` (`id_veiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Tabela PAGAMENTO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pagamento` (
  `id_pagamento` INT NOT NULL AUTO_INCREMENT,
  `id_ordem_servico` INT NOT NULL,
  `tipo` ENUM('dinheiro', 'cartao_credito', 'cartao_debito', 'pix') NOT NULL,
  `status` ENUM('pendente', 'realizado') NOT NULL,
  `data` DATE NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_pagamento`),
  INDEX `fk_pagamento_ordem_servico_idx` (`id_ordem_servico`),
  CONSTRAINT `fk_pagamento_ordem_servico`
    FOREIGN KEY (`id_ordem_servico`)
    REFERENCES `ordem_servico` (`id_ordem_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Tabela PECA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peca` (
  `id_peca` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `valor_unitario` DECIMAL(10,2) NOT NULL,
  `quantidade_estoque` INT NOT NULL,
  `fornecedor` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_peca`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- RELACIONAMENTO FUNCIONARIO x ORDEM_SERVICO (N:N)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `funcionario_ordem_servico` (
  `id_funcionario` INT NOT NULL,
  `id_ordem_servico` INT NOT NULL,
  PRIMARY KEY (`id_funcionario`, `id_ordem_servico`),
  CONSTRAINT `fk_funcionario_ordem_servico_funcionario`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_ordem_servico_ordem_servico`
    FOREIGN KEY (`id_ordem_servico`)
    REFERENCES `ordem_servico` (`id_ordem_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- RELACIONAMENTO ORDEM_SERVICO x PECA (N:N)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordem_servico_peca` (
  `id_ordem_servico` INT NOT NULL,
  `id_peca` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `valor_unitario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_ordem_servico`, `id_peca`),
  CONSTRAINT `fk_ordem_servico_peca_ordem_servico`
    FOREIGN KEY (`id_ordem_servico`)
    REFERENCES `ordem_servico` (`id_ordem_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordem_servico_peca_peca`
    FOREIGN KEY (`id_peca`)
    REFERENCES `peca` (`id_peca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;

-- Restaura as configurações originais do MySQL
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
