-- MySQL Script generated by MySQL Workbench
-- Sun Nov  9 00:24:30 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetoautomov
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetoautomov
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetoautomov` DEFAULT CHARACTER SET utf8 ;
USE `projetoautomov` ;

-- -----------------------------------------------------
-- Table `projetoautomov`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoautomov`.`funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(65) NOT NULL,
  `telefone` CHAR(11) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `cargo` ENUM('Mecânico', 'Atendente', 'Gerente') NOT NULL,
  PRIMARY KEY (`id_funcionario`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
  
-- "motor" usado pela tabela. 
ENGINE = InnoDB;
-- Permite usar chaves estrangeiras
 


-- -----------------------------------------------------
-- Table `projetoautomov`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoautomov`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(65) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `telefone` CHAR(11) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoautomov`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoautomov`.`veiculo` (
  `id_veiculo` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `marca` VARCHAR(30) NOT NULL,
  `modelo` VARCHAR(30) NOT NULL,
  `ano` CHAR(4) NULL,
  `cor` VARCHAR(30) NULL,
  `placa` CHAR(8) NOT NULL,
  `motor` CHAR(10) NOT NULL,
  PRIMARY KEY (`id_veiculo`),
  INDEX `fk_veiculo_cliente_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_veiculo_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `projetoautomov`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoautomov`.`ordem_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoautomov`.`ordem_servico` (
  `id_ordem_servico` INT NOT NULL AUTO_INCREMENT,
  `id_veiculo` INT NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  `descricao_problema` TEXT NOT NULL,
  `acao_realizada` TEXT NOT NULL,
  `status` ENUM('aberta', 'em_andamento', 'concluída', 'cancelada') NOT NULL,
  PRIMARY KEY (`id_ordem_servico`),
  INDEX `fk_ordem_servico_veiculo_idx` (`id_veiculo` ASC) VISIBLE,
  CONSTRAINT `fk_ordem_servico_veiculo`
    FOREIGN KEY (`id_veiculo`)
    REFERENCES `projetoautomov`.`veiculo` (`id_veiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoautomov`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoautomov`.`pagamento` (
  `id_pagamento` INT NOT NULL AUTO_INCREMENT,
  `id_ordem_servico` INT NOT NULL,
  `tipo` ENUM('dinheiro', 'cartao_credito', 'cartao_debito', 'pix') NOT NULL,
  `status` ENUM('Pendente', 'Realizado') NOT NULL,
  `data` DATE NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_pagamento`),
  INDEX `fk_pagamento_cliente_idx` (`id_ordem_servico` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento_ordem_servico`
    FOREIGN KEY (`id_ordem_servico`)
    REFERENCES `projetoautomov`.`ordem_servico` (`id_ordem_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoautomov`.`peca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoautomov`.`peca` (
  `id_peca` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `valor_unitario` DECIMAL(10,2) NOT NULL,
  `quantidade_estoque` INT NOT NULL,
  `fornecedor` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_peca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table RELACIONAMENTO `projetoautomov`.`funcionario_ordem_servico` 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoautomov`.`funcionario_ordem_servico` (
  `id_funcionario` INT NOT NULL,
  `id_ordem_servico` INT NOT NULL,
  PRIMARY KEY (`id_funcionario`, `id_ordem_servico`),
  INDEX `fk_funcionario_ordem_servico_ordem_servico_idx` (`id_ordem_servico` ASC) VISIBLE,
  INDEX `fk_funcionario_ordem_servico_funcionario_idx` (`id_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_ordem_servico_funcionario`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `projetoautomov`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_ordem_servico_ordem_servico`
    FOREIGN KEY (`id_ordem_servico`)
    REFERENCES `projetoautomov`.`ordem_servico` (`id_ordem_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table RELACIONAMENTO `projetoautomov`.`ordem_servico_peca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoautomov`.`ordem_servico_peca` (
  `id_ordem_servico` INT NOT NULL,
  `id_peca` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `valor_unitario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_ordem_servico`, `id_peca`),
  INDEX `fk_ordem_servico_peca_peca_idx` (`id_peca` ASC) VISIBLE,
  INDEX `fk_ordem_servico_peca_ordem_servico_idx` (`id_ordem_servico` ASC) VISIBLE,
  CONSTRAINT `fk_ordem_servico_peca_ordem_servico`
    FOREIGN KEY (`id_ordem_servico`)
    REFERENCES `projetoautomov`.`ordem_servico` (`id_ordem_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordem_servico_peca_peca`
    FOREIGN KEY (`id_peca`)
    REFERENCES `projetoautomov`.`peca` (`id_peca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
