-- MySQL Script generated by MySQL Workbench
-- Sun Nov  9 02:32:37 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoa` (
  `id_pessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(65) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `rg` CHAR(9) NOT NULL,
  `telefone` CHAR(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pessoa`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `id_funcionario` INT NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `cargo` ENUM('Mecânico', 'Atendente', 'Gerente') NOT NULL,
  PRIMARY KEY (`id_funcionario`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_pessoa`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `mydb`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id_cliente` INT NOT NULL,
  `data_cadastro` DATE NOT NULL DEFAULT (CURRENT_DATE),
  PRIMARY KEY (`id_cliente`),
  CONSTRAINT `fk_cliente_pessoa1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mydb`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`veiculo` (
  `id_veiculo` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `marca` VARCHAR(30) NOT NULL,
  `modelo` VARCHAR(30) NOT NULL,
  `ano` CHAR(4) NULL,
  `cor` VARCHAR(30) NULL,
  `placa` CHAR(8) NOT NULL,
  `motor` CHAR(10) NOT NULL,
  PRIMARY KEY (`id_veiculo`, `id_cliente`),
  INDEX `fk_veiculo_cliente1_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_veiculo_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mydb`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ordem_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ordem_servico` (
  `id_ordem_servico` INT NOT NULL AUTO_INCREMENT,
  `id_veiculo` INT NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  `descricao_problema` TEXT NOT NULL,
  `acao_realizada` TEXT NOT NULL,
  `status` ENUM('aberta', 'em_andamento', 'concluída', 'cancelada') NOT NULL,
  PRIMARY KEY (`id_ordem_servico`, `id_veiculo`),
  INDEX `fk_ordem_servico_veiculo1_idx` (`id_veiculo` ASC) VISIBLE,
  CONSTRAINT `fk_ordem_servico_veiculo1`
    FOREIGN KEY (`id_veiculo`)
    REFERENCES `mydb`.`veiculo` (`id_veiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pagamento` (
  `id_pagamento` INT NOT NULL AUTO_INCREMENT,
  `id_ordem_servico` INT NOT NULL,
  `tipo` ENUM('dinheiro', 'cartao_credito', 'cartao_debito', 'pix') NOT NULL,
  `status` ENUM('Pendente', 'Realizado') NOT NULL,
  `data` DATE NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_pagamento`, `id_ordem_servico`),
  INDEX `fk_pagamento_cliente1_idx` (`id_ordem_servico` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento_ordem_servico`
    FOREIGN KEY (`id_ordem_servico`)
    REFERENCES `mydb`.`ordem_servico` (`id_ordem_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`peca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`peca` (
  `id_peca` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `valor_unitario` DECIMAL(10,2) NOT NULL,
  `quantidade_estoque` INT NOT NULL,
  `fornecedor` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_peca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario_ordem_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario_ordem_servico` (
  `id_funcionario` INT NOT NULL,
  `id_ordem_servico` INT NOT NULL,
  PRIMARY KEY (`id_funcionario`, `id_ordem_servico`),
  INDEX `fk_funcionario_has_ordem_servico_ordem_servico1_idx` (`id_ordem_servico` ASC) VISIBLE,
  INDEX `fk_funcionario_has_ordem_servico_funcionario1_idx` (`id_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_has_ordem_servico_funcionario1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `mydb`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_has_ordem_servico_ordem_servico1`
    FOREIGN KEY (`id_ordem_servico`)
    REFERENCES `mydb`.`ordem_servico` (`id_ordem_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ordem_servico_peca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ordem_servico_peca` (
  `id_ordem_servico` INT NOT NULL,
  `id_peca` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `valor_unitario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_ordem_servico`, `id_peca`),
  INDEX `fk_ordem_servico_has_peca_peca1_idx` (`id_peca` ASC) VISIBLE,
  INDEX `fk_ordem_servico_has_peca_ordem_servico1_idx` (`id_ordem_servico` ASC) VISIBLE,
  CONSTRAINT `fk_ordem_servico_has_peca_ordem_servico1`
    FOREIGN KEY (`id_ordem_servico`)
    REFERENCES `mydb`.`ordem_servico` (`id_ordem_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordem_servico_has_peca_peca1`
    FOREIGN KEY (`id_peca`)
    REFERENCES `mydb`.`peca` (`id_peca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `id_pessoa` INT NOT NULL,
  `estado` CHAR(2) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `rua` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `complemento` VARCHAR(30) NULL,
  PRIMARY KEY (`id_endereco`, `id_pessoa`),
  INDEX `fk_endereco_pessoa1_idx` (`id_pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_pessoa1`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `mydb`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
