-- MySQL Script generated by MySQL Workbench
-- Sun Nov  9 02:32:37 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- Revisado por Mateus em 09/11/2025

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- Schema db_automov
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_automov` DEFAULT CHARACTER SET utf8 ;
USE `db_automov` ;

-- -----------------------------------------------------
-- Tabela `pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_automov`.`pessoa` (
  `id_pessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(65) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `rg` CHAR(9) NOT NULL,
  `telefone` CHAR(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pessoa`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) ,
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC) 
)
-- ENGINE define o "motor" da tabela. InnoDB permite usar FKs e transações.
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Tabela `funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_automov`.`funcionario` (
  `id_funcionario` INT NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `cargo` ENUM('Mecânico', 'Atendente', 'Gerente') NOT NULL,
  PRIMARY KEY (`id_funcionario`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) ,
  CONSTRAINT `fk_funcionario_pessoa`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `db_automov`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Tabela `cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_automov`.`cliente` (
  `id_cliente` INT NOT NULL,
  `data_cadastro` DATE NOT NULL DEFAULT (CURRENT_DATE),
  PRIMARY KEY (`id_cliente`),
  CONSTRAINT `fk_cliente_pessoa`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `db_automov`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Tabela `veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_automov`.`veiculo` (
  `id_veiculo` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `marca` VARCHAR(30) NOT NULL,
  `modelo` VARCHAR(30) NOT NULL,
  `ano` CHAR(4) NULL,
  `cor` VARCHAR(30) NULL,
  `placa` CHAR(8) NOT NULL,
  `motor` CHAR(10) NOT NULL,
  PRIMARY KEY (`id_veiculo`),
  INDEX `fk_veiculo_cliente_idx` (`id_cliente` ASC) ,
  CONSTRAINT `fk_veiculo_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `db_automov`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Tabela `ordem_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_automov`.`ordem_servico` (
  `id_ordem_servico` INT NOT NULL AUTO_INCREMENT,
  `id_veiculo` INT NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  `descricao_problema` TEXT NOT NULL,
  `acao_realizada` TEXT NOT NULL,
  `status` ENUM('aberta', 'em_andamento', 'concluída', 'cancelada') NOT NULL,
  PRIMARY KEY (`id_ordem_servico`),
  INDEX `fk_ordem_servico_veiculo_idx` (`id_veiculo` ASC) ,
  CONSTRAINT `fk_ordem_servico_veiculo`
    FOREIGN KEY (`id_veiculo`)
    REFERENCES `db_automov`.`veiculo` (`id_veiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Tabela `pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_automov`.`pagamento` (
  `id_pagamento` INT NOT NULL AUTO_INCREMENT,
  `id_ordem_servico` INT NOT NULL,
  `tipo` ENUM('dinheiro', 'cartao_credito', 'cartao_debito', 'pix') NOT NULL,
  `status` ENUM('Pendente', 'Realizado') NOT NULL,
  `data` DATE NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_pagamento`),
  INDEX `fk_pagamento_cliente_idx` (`id_ordem_servico` ASC) ,
  CONSTRAINT `fk_pagamento_ordem_servico`
    FOREIGN KEY (`id_ordem_servico`)
    REFERENCES `db_automov`.`ordem_servico` (`id_ordem_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Tabela `peca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_automov`.`peca` (
  `id_peca` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `valor_unitario` DECIMAL(10,2) NOT NULL,
  `quantidade_estoque` INT NOT NULL,
  `fornecedor` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_peca`)
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- RELACIONAMENTO FUNCIONARIO x ORDEM_SERVICO (N:N)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_automov`.`funcionario_ordem_servico` (
  `id_funcionario` INT NOT NULL,
  `id_ordem_servico` INT NOT NULL,
  PRIMARY KEY (`id_funcionario`, `id_ordem_servico`),
  INDEX `fk_funcionario_ordem_servico_ordem_servico_idx` (`id_ordem_servico` ASC) ,
  INDEX `fk_funcionario_ordem_servico_funcionario_idx` (`id_funcionario` ASC) ,
  CONSTRAINT `fk_funcionario_ordem_servico_funcionario`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `db_automov`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_ordem_servico_ordem_servico`
    FOREIGN KEY (`id_ordem_servico`)
    REFERENCES `db_automov`.`ordem_servico` (`id_ordem_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- RELACIONAMENTO ORDEM_SERVICO x PECA (N:N)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_automov`.`ordem_servico_peca` (
  `id_ordem_servico` INT NOT NULL,
  `id_peca` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `valor_unitario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_ordem_servico`, `id_peca`),
  INDEX `fk_ordem_servico_peca_peca_idx` (`id_peca` ASC) ,
  INDEX `fk_ordem_servico_peca_ordem_servico_idx` (`id_ordem_servico` ASC) ,
  CONSTRAINT `fk_ordem_servico_peca_ordem_servico`
    FOREIGN KEY (`id_ordem_servico`)
    REFERENCES `db_automov`.`ordem_servico` (`id_ordem_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordem_servico_peca_peca`
    FOREIGN KEY (`id_peca`)
    REFERENCES `db_automov`.`peca` (`id_peca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Tabela `endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_automov`.`endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `id_pessoa` INT NOT NULL,
  `estado` CHAR(2) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `rua` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `complemento` VARCHAR(30) NULL,
  PRIMARY KEY (`id_endereco`),
  INDEX `fk_endereco_pessoa_idx` (`id_pessoa` ASC) ,
  CONSTRAINT `fk_endereco_pessoa`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `db_automov`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;

-- Restaura as configurações originais do MySQL
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;